### PR TITLE
Set up GitHub actions and a simple site

### PR DESCRIPTION
**Pull request by jonchang**
Prior to merging, an owner must generate an API token with the `public_repo` scope and add it as a secret to the repository with the name `GITHUB_ACCESS_KEY`.

### CODE REVIEW

**Comment by josephwb** [comment]
i don't really understand what this is about.

does this change how i push merge?

**Comment by jonchang** [comment]
This pull request:

* replaces travis builds with github actions (they run faster and imo will be more supported going forward)
* tests on both macos and linux
* pushes a simple site to github pages that just contains the contents of each command's `--help`

**Comment by jonchang** [comment]
Once i know that CI deploys are working I'll set up a better site with documentation ported over from the wiki.

**Comment by josephwb** [comment]
Thanks for that. So:

>Prior to merging, an owner must generate an API token with the public_repo scope and add it as a secret to the repository with the name GITHUB_ACCESS_KEY

you mean a token has to be generated for _this_ merge, not all subsequent merges. I guess I interpreted that wrong.

**Comment by jonchang** [comment]
Yes, a secret only has to be added once.

**Comment by josephwb** [comment]
Hey @jonchang I'd like to move forward on this. I believe there are conflicts bc of a big recent merge.

Can this PR be updated, or should we start a fresh one?

Also, from what I've read, it sounds prudent to keep travis around for a bit while the new testing process is ironed out. Sounds reasonable?

**Comment by josephwb** [comment]
A pared-down version of this is now up-and-running. Thanks @jonchang for all of the help. I only wish I was smart enough to facilitate this when you first proffered it.

**Pull request closed without merging**
